### ISSUE TITLE
v6: sockets left open after calling Client.end

### ISSUE THREAD

**Issue by jedwards1211** [brianc/node-postgres#1545]
No idea if you're willing to consider fixes with this, but unfortunately I'm stuck with v6.4.2 right now because Sequelize doesn't support v7 yet.

According to [`wtfnode`](https://github.com/myndzi/wtfnode), a socket created by `pg` is left open even after I call `sequelize.close()` (and I verified that `Client.end()` got called in `pg`).  I'm wondering if it's simply because `Connection.end()` never calls `this.stream.close()`?

```
[WTF Node?] open handles:
- File descriptors: (note: stdio always exists)
  - fd 1 (tty) (stdio)
  - fd 2 (tty) (stdio)
- Sockets:
  - 127.0.0.1:55731 -> 127.0.0.1:5432
    - Listeners:
      - connect: (anonymous) @ /Users/andy/iron-pi-webapp/node_modules/pg/lib/connection.js:73
- Timers:
Unable to determine callsite for "Function". Did you require `wtfnode` at the top of your entry point?
  - (2000 ~ 2 s)  @ unknown:0
```
