### ISSUE TITLE
Can't connect to database (docker)

### ISSUE THREAD

**Issue by botiapa** [brianc/node-postgres#2256]
My postgres and node server are in the same docker-compose. If I run the node server outside its container, it can successfully connect to the db even if it is in a container itself. However the node server cannot connect if its inside a container. I'm creating a pool like this: 
```
this.pool = new Pool({
			  user: UID,
			  host: SERVER,
			  database: DATABASE,
			  password: PASSWORD,
			  idleTimeoutMillis: 15000,
  			  connectionTimeoutMillis: 3000, 
			  max: 15 
                     });
```
And it throws this error when I try to query something:
`err: Error: Connection terminated due to connection timeout`

Even though when I run psql inside the node container, I can connect, so I don't think it's something to do with networking.

**Comment by charmander** [comment]
Are you sure `SERVER` is the same between Node and psql? Which versions of Node and pg are you using?

**Comment by botiapa** [comment]
Yeah, I'm pretty sure, I just tested it. I'm using docker compose to set up a connection between the containers like this(I replaced both the username and password to 'postgres' for convenience):
```
version: "3"
services:
  postgres:
    container_name: "excusegen_db"
    build: 
      context: .
      dockerfile: ./docker/db/Dockerfile
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  app:
    container_name: "excusegen_app"
    links:
      - postgres
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
```

And then connecting to the database via the hostname "postgres". I just connected to it with using psql from the app container like this:
psql --host=postgres -U postgres

The postgres version is **13beta1** and the nodejs version is **v14.4.0**
